import * as ko from "knockout";
import _changeTracker = require("./changetracker");
export declare const ChangeTracker: typeof _changeTracker;
import * as _extenders from "./extenders";
export declare type DelayedSubscribable<T, U extends ko.Subscribable<T>> = _extenders.DelayedSubscribable<T, U>;
export declare type DelayedObservable<T> = _extenders.DelayedObservable<T>;
export import extenders = _extenders;
export * from "./observable";
export * from "./purifier";
export * from "./utils";
